- README.md
> Add reeha's profile

- README.md
> Sort profiles alphabetically

- README.md
Added alphabetically. I hope it's fine.
> chore: added anurag hazra readme

- README.md
> Added my profile on the README

- README.md
- Hey, Eddie I have updated the README and added my profile to it.
> Added my profile to the README

- README.md
I have added my GitHub profile at the end, please let me know if I done something wrong.
> Added My GitHub Profile

- data.json
> Name RemcoHalman added

- CONTRIBUTING.md
This Pull request fixes issue #74 
Corrected the typo in contributing.md
> Corrected typo in contributing.md

- data.json
Updated my profile and image is from issue #84
> Updated my profile aakarshteja #84

- data.json
Added my profile in `data.json`
Fixes #86
> Updated data.json with my profile

- data.json
> Updated Aniket-Singh

- .github/workflows/main.yml
- data.json
> Updated Github actions

- .github/workflows/main.yml
Changed the main.yml with reference from the below link
https://github.com/EddieJaoudeCommunity/awesome-github-profiles/blob/main/.github/workflows/main.yml#L10
> changed the uses in main.yml solved #90

- data.json
updated data.json with user details of [NirmalSilwal profile](https://github.com/NirmalSilwal)
> added Nirmal Silwal profile in list

- data.json
**Added Savio Martin** to `data.json` **with image and issue number: 10**
Hope it makes sense.
Thank you
> Added Savio Martin to the list

- data.json
This PR fixes #99 
@AllanRegush @eddiejaoude  please have a review
> updated formatting

- data.json
Request to add this profile snapshot in the list.
> Added Sharannyo Basu to JSON

- data.json
<p align="center"><img src="https://i.ibb.co/5YCB30Y/Hritik-Read-Me.jpg" alt="Hritik-Read-Me" border="0"></p>
> Hritik Jaiswal Github ReadMe

- data.json
Added My Profile
Issue #118 
GitHub Username: Pratham31
> Added my GitHub(Profile) <Pratham31>

- data.json
> Added my GitHub Profile #121

- data.json
Issue #125
Hope I've done it correctly with 3 images. Let me know if I need to change anything.
M
> Add Michelle Sandford

- data.json
> Updated JSON data.

- data.json
> Added my required info

- data.json
Closes #151 
Created during @eddiejaoude livestream https://www.youtube.com/watch?v=LyTUj6YQoBo
> Add AnkushSinghGandhi's profile

- data.json
> added my profile :smile:

- data.json
> update Dedar Alam Profile

- data.json
> fix: format json

- data.json
- I followed the instructions to add the photo of my github profile in the README file.
- So please merge this pull request to the main branch.
> Add my github profile in data.json

- data.json
Added Jonah Lawrence's profile readme
https://github.com/DenverCoder1/DenverCoder1
> Added #209 (Jonah Lawrence)

- data.json
<br/>
GitHub Profile link: <a href="https://github.com/vinzvinci98/vinzvinci98">https://github.com/vinzvinci98/vinzvinci98</a>
> Added Vincent Villafuerte GitHub profile

- data.json
Added my json object for my profile image.
> Update data.json file

- README.md
> fix: prettier recommended changes

- data.json
closes #300 
Fixes prettier warning from our github action
> fix: trailing space #300

- .github/workflows/main.yml
closes #298 
Changes Readme update github action to reflect organisation name change.
> fix: update main github action #298

- README.md
I thought it would be good if the Readme shows some more information on how to open a pull request and with `resolve #issunumber` the issues will automatically be closed.
May we also can add a PR Template with `resolve #issuenumber` in it 🚀
> Add some additional context for opening a PR

- data.json
> Danishulhassan7

- data.json
> add schmelto

- data.json
> Add krniya

- data.json
> add jaypatel31

- data.json
> add rishabh062

- data.json
> add Cas Martens 

- data.json
> add SubhamRaoniar28

- data.json
> Add rohank2502

- data.json
> add ChinmayMhatre

- data.json
> add KhushiSharma22

- data.json
This PR is referring to issue #429
> @yashsehgal profile image added

- data.json
> add karan-ksrk

- data.json
> add anotherwebguy

- data.json
> rishabhrathore055

- data.json
> Add Sam-Varghese(#467)

- README.md
see [here](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/issues/163)
> fix: discord link

- data.json
> Update vinzvinci GitHub profile

- README.md
- data.json
Just checking if this was the prettifier issue
> fix: prettifier

- data.json
> Add SulthanNK

- data.json
> add priyaankamishra

- data.json
> add @Saatvik21

- data.json
> add wordssaysalot

- data.json
> Add ibby360

- data.json
> add thejaswin123

- data.json
> Add ImAvinashSharma

- data.json
> add amino19

- data.json
> add ayushtamra

- data.json
> add Ayushparikh-code

- data.json
> add Rupam-Shil

- data.json
> add nayakastha

- data.json
> Add CyberBoyAyush

- data.json
> fix: prettier issue

- data.json
> add 13yadav

- data.json
> gagan3012 

- data.json
> add AmpoluNisa03

- data.json
> add adityamangal1

- data.json
> Add Panquesito7

- data.json
> add Beven Nyamande

- data.json
> add hrittikhere

- data.json
> add tips367

- data.json
> add jayesh-srivastava

- data.json
> add hanshulll

- data.json
IssueNumber same, Link Updated.
_Ready to Merge!_ :slightly_smiling_face: 
Related to #582
> fix: aminos 🇮🇳 Updated 

- data.json
> Add UtkarshMishra12

- data.json
> added HareerSakhi's profile

- data.json
> Added rohit yadav profile

- data.json
> Add MrSlimCoder

- data.json
> Add hrishikeshnikam2000

- data.json
> add bloedboemmel

- data.json
> add rajivranjanmars

- data.json
resolve #621 
duplicate with #622
> SahityaRoy Update data.json

- data.json
> add Subathra19

- data.json
> add adityagarde

- data.json
> add vineelsai26

- data.json
> add msaaddev

- data.json
> add bhagatpratham

- data.json
> add iamgunjan

- data.json
Add my profile data
Resolve #641
> Add Vasudev Jaiswal 

- data.json
> add FayasNoushad

- data.json
> Add KukretiShubham

- data.json
Updated My name, and readme. thanks
Resolve #650
> Updated my profile name, readme

- data.json
> add Harkirat Singh

- data.json
> add Anikcb

- data.json
> add ahamedbasha-n

- README.md
Things added/changed:
- Fixed the GitHub Action link in the `README.md` file.
> fix: link in `README.md`

- data.json
> add  BADSHAH-AMAN

- data.json
> add mahatorakesh

- data.json
> Krishnapro

- data.json
> add devesh-anand

- data.json
> Add grawish

- data.json
> add chetan-2002

- data.json
> add shreyaansjain06

- data.json
> Add hariketsheth to the list

- data.json
> Add ZaidKhan2002

- data.json
> Add Vanshikapandey30 

- data.json
> add DarshGupta1910

- data.json
> add AaquibAli

- data.json
> Add Rohan Gupta to the list

- data.json
> fix: Add SayantaniDeb

- data.json
> fix: Add cankush625 GitHub profile

- data.json
> fix: Add anubhav201241 to the list

- data.json
> fix: Add shashank-indukuri

- data.json
> add Jas-Script

- data.json
> feat(profiles): add qwe123pro

- data.json
> fix: Add Antonio Martínez to the list

- data.json
> add ckvignesh

- data.json
> add Antonio-Riccelli

- data.json
> add gouravkhunger

- data.json
> add kshitijarvikar

- data.json
> fix: Add Tara Choudhary to the list

- data.json
> add Aleksey-Voko

- data.json
> add rohansaini886

- data.json
> add Kira272921

- data.json
> feat(add-profile): krishguptadev

- data.json
> fix: Add Jaideep Guntupalli to the list

- data.json
> fix: Add Sriniketh J to the list

- data.json
> fix: Add Khushi0321

- data.json
> fix: add avneesh0612

- CODE_OF_CONDUCT.md
> docs: update email

- data.json
> fix: Add AnishDe12020

- data.json
> fix: add AnuragThePathak

- profiles/Pradumnasaraf.json
> fix: add pradumnasaraf

- README.md
Things added/changed:
- Update readme JSON's example content.
> docs: update readme JSON's example content

- profiles/ravithemore.json
> fix: add ravithemore

- profiles/kumarsonsoff3.json
> fix: add kumarsonsoff3

- .github/pull_request_template.md
Things added/changed:
- Improve the pull request template.
> docs: improve the pull request template

- .github/pull_request_template.md
- README.md
- package.json
- profiles/Pradumnasaraf.json
- profiles/codlipa.json
- profiles/kumarsonsoff3.json
- profiles/ravithemore.json
- profiles/samuelbartels20.json
Things added/changed:
- Fix Prettier issues.
> fix: Prettier issues

- .github/pull_request_template.md
- README.md
- Changed from `add <your-username>` to `fix: add <your-username>` in `README.md`.
- Changed from `fix: Add <your-username>` to `fix: add <your-username>` in `pull_request_template.md`.
- Fixes #907.
> docs: Updated PR title in Readme an PR template.

- profiles/samarfatimajaffri.json
resolves #929
---
- I have added my profile readme.
- It might inspire someone and help them create their awesome profile.
- I have also attributed to other GitHub repos and illustration's designer, which is necessary to do if you are using someone's else resources. So it also might help others find useful resources for themselves.
> fix: add samarfatimajaffri

- profiles/devesh2511.json
> fix: add devesh2511

- profiles/matthewraymondh.json
> fix: add matthewraymondh

- profiles/adityathakekar.json
> fix: add adityathakekar

- profiles/ManinderSidhu.json
> fix: add github4maninder

- profiles/AdrianaLuisaDelaCruz.json
> fix: add adrianaluisadc

- profiles/kishanrajput23.json
> fix: add kishanrajput23

- profiles/krishguptadev.json
I've got a new profile, so this is a screenshot update.
> chore: update profile

- profiles/TheSlimCoder.json
Hello team,
Recently I changed my user name on GitHub and updated it to new one from MrSlimCoder to TheSlimCoder for my website TheSlimCoder.com.
so in this PR I changed username to TheSlimCoder.
resolves #`issueNumber`
---
> Update profile json from MrSlimCoder to TheSlimCoder

- profiles/Mustafiz04.json
resolve #959
resolves #`issueNumber`
---
> fix: add Mustafiz04

- profiles/arpanaditya.json
> fix: add arpanaditya

- profiles/Zafeer-R.json
resolve #966
---
I have added the updated GitHub profile with this PR.
> fix: add Zafeer-R

- profiles/Samadrita-Shaw.json
resolve #968
---
My updated README's screenshot.
> fix: add Samadrita-Shaw

- profiles/abhisheks008.json
resolves #970 
---
This PR adds the `abhisheks008.json` file in the `profiles` directory.
> fix: add abhisheks008

- profiles/elishahyousaf.json
> fix: add <elishahyousaf>

- profiles/tinoschroeter.json
> fix: add tinoschroeter

- _config.yml
- profiles/SparkScratch-P.json
resolves #976 
---
The theme was not working on the Github Page. So, I edited and activated the Cayman Jekyll theme.
> fix: add SparkScratch-P

- profiles/Susmita-Dey.json
> fix: add <Susmita-Dey>

- profiles/IAMSKJha.json
> chore: add IAMSKJha

- profiles/aritra-tech.json
> fix: add aritra-tech

- profiles/GeekLord04.json
> fix: add GeekLord04

- profiles/binayshaw7777.json
> fix: add binayshaw7777

- profiles/binitrajshah7.json
resolves #998 
---
- Adds New GitHub Profile to the Repository
- I have mistakenly given the wrong issueId in my profile binitrajshah7.json file and I'm not able to edit it as it is not in the main branch sooner the file gets merged to the main branch I would edit it and commit the necessary changes. 
- Original issueID : 998
- Misktaken issueID in .json file : 999
> fix: binitrajshah7.json

- profiles/sansk.json
> fix: add sansk

- profiles/kenhorlador.json
> fix: add kenhorlador

- profiles/karanS08.json
> fix: add karanS08

- profiles/LudovicoSforza.json
> fix: add Ludovico Sforza

- profiles/kabir0x17.json
> add kabir0x17

- profiles/Candida.json
- profiles/Candida18.json
> fix: add Candida18

- profiles/krshdev.json
> fix: username change

- profiles/shubhamghb.json
> Profile shubhamghb

- _layouts/default.html
- profiles/vasantisuthar.json
resolves #1041 
- [x ] Name the PR `fix: add <your-username>`.
- [ x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x ] You've linked the PR to the correct issue.
---
- [ x] Changes made in this PR are mentioned below
- [ x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ x] I acknowledge that all my contributions will be made under the project's license.
- [x ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)
> fix: add vasantisuthar

- profiles/Debaghosh.json
> fix: add debaghosh

- profiles/shashank2906.json
> fix: add shashank2906

- profiles/NnadiVictory25.json
> fix: add NnadiVictory25

- profiles/CodingSpecies.json
I have updated my profile screenshot. Thank you.
> Updates CodingSpecies profile screenshot

- profiles/benjaminmichaelis.json
> fix: add benjaminmichaelis

- profiles/MilkFlavor.json
> Add MilkFlavor

- profiles/mrkc2303.json
> fix: add mrkc2303

- profiles/ronwaller.json
resolves #1070
- [ x] Name the PR `fix: add <your-username>`.
- [ x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ x] You've linked the PR to the correct issue.
---
> fix: add RonWaller

- profiles/abh139.json
> fix: add abh139

- profiles/Hema Priya V.json
> fix: add TheProgrammer565

- profiles/Pritam0077.json
> fix:add Pritam0077

- profiles/Jitesh117.json
> fix: add Jitesh117

- profiles/gefgu.json
> fix: add gefgu

- profiles/codersalman.json
> fix: add codersalman

- profiles/The-Shivam-garg.json
> fix: add The-Shivam-garg

- profiles/sagar0-0.json
resolves #1101
---
fixes #1101
> fix: add Sagar0-0

- evle.json
> fix: add evle

- profiles/bocan.json
> fix: add bocan

- README.md
resolves #1052 
---
- The issue number #1052 in which I've added the link to profiles.md inside the main readme.md file
- Now the use will be able to see the profiles from the GitHub repository itself
> Added Link to pofiles.md in readme.md  

- profiles/Santosh1176.json
> fix: add Santosh1176

- profiles/amelia2802.json
> fix: add amelia2802

- profiles/Shivam-Katare.json
> fix: add Shivam-Katare

- profiles/SubhadeepZilong.json
resolves #1132
---
- SubhadeepZilong.json file has been added
> fix: add SubhadeepZilong

- profiles/tarunbisht-24.json
> fix: add tarunbisht-24

- profiles/prasanta10.json
> fix: add prasanta10

- profiles/SohamRatnaparkhi.json
resolve #1117 
---
This PR involves the addition of my profile to `awesome profiles`.
> fix: add SohamRatnaparkhi 

- profiles/Sulagna-Dutta-Roy.json
> fix: add Sulagna-Dutta-Roy

- profiles/eshan-sharma.json
User profile created.
resolves #1136
> fix: add eshan-sharma.json (resolve #1136)

- profiles/arth2002.json
> fix: add arth2002

- profiles/iamrahul8.json
> fix: add iamrahul8

- profiles/kasuncfdo.json
> fix: add kasuncfdo

- profiles/Sumit-jr.json
> Added Sumit-jr file

- profiles/mrkrishnaagarwal.json
resolves #1174 
---
People will get inspired!
> fix: add MrKrishnaAgarwal 

- profiles/preccrep.json
> fix: add preccrep

- thelabuzov.json
> add thelabuzov

- profiles/abhinandanraj.json
> fix: add abhinandanraj

- profiles/kumar-saurabh.json
resolves #https://github.com/EddieHubCommunity/awesome-github-profiles/issues/1179
---
> fix: add ksaurabh4

- profiles/enn-dee.json
resolves #1176
---
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix
> fix: Add enn-dee

- profiles/KaranChandekar.json
> fix: add KaranChandekar

- profiles/Adit0507.json
> fix: add Adit0507

- profiles/ianskie26.json
> fix: add ianskie26

- jeremiey.json
> fix: add jeremiey

- profiles/tarunmankar.json
> fix: add tarunmankar

- profiles/route-2.json
> fix: add route-2

- profiles/cosmicqbit.json
> Fix: Add cosmicqbit

- profiles/ayushlohmod.json
> fix: add ayushlohmod

- profiles/VinitHemadri.json
> fix: add Vinitvh

- profiles/bishtanuj.json
resolves #1252 
- [ *] Name the PR `fix: add <your-username>`.
- [ *] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ *] You've linked the PR to the correct issue.
---
> fix: add bishtanuj

- profiles/Exoutia.json
> fix: add Exoutia

- profiles/Roshan-Sharma.json
> fix: add Roshan-Sharma.json

- profiles/Obito9596.json
> Fix :add Obito9596

- profiles/MadhuSaini22.json
resolves #1266 
- [Y] Name the PR `fix: add MadhuSaini22`.
- [Y] You've added file named `MadhuSaini22` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [Y] You've linked the PR to the correct issue.
---
- [Y] Changes made in this PR are mentioned below
- [Y] Search previous suggestions before making a new one, as yours may be a duplicate.
- [Y] I acknowledge that all my contributions will be made under the project's license.
- [Y] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)
> add MadhuSaini22

- profiles/marcokumu.json
> fix: add marcokumu

- profiles/aparna2071.json
> fix: add aparna2071

- profiles/jesufemigan.json
> fix: add jesufemigan

- profiles/ChathurikaDissanayaka.json
> fix: add ChathurikaDissanayaka

- profiles/RayanAbid.json
https://github.com/EddieHubCommunity/awesome-github-profiles/issues/1280
resolves #1280 
- [✅ ] Name the PR `fix: add <your-username>`.
- [✅  ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ✅ ] You've linked the PR to the correct issue.
> fix: add <RayanAbid>

- profiles/heyyfurqan.json
> fix: add heyyfurqan

- profiles/razaahmad333.json
> fix: add razaahmad333

- profiles/TechstarMahesh.json
> fix: add techstarMahesh

- profiles/poonam-adlakha.json
Adding my profile to list of Awesome-GitHub-profiles
resolves #1305
---
> fix: add poonam-adlakha

- profiles/sachinparihar.json
> fix: Add sachinparihar

- profiles/Prasad-mutnale.json
> fix: add Prasad-mutnale

- profiles/badbatunde.json
> fix: add badbatunde

- profiles/lubnafathima.json
> fix: add lubnafathima

- profiles/anekemichael.json
> fix: add anekemichael

- profiles/johnmiicheal.json
> add johnmiicheal

- profiles/TenTraicion.json
> fix: add TenTraicion

- profiles/shreyas1925.json
> fix: add shreyas1925

- profiles/makendrang.json
> fix: add makendrang

- profiles/FarhAnonymous.json
> fix: add FarhAnonymous

- profiles/ifeanyichukwuOtiwa-sports.json
> fix: add ifeanyichukwuOtiwa-sports :tada:

- profiles/haldaranup.json
> fix: add haldaranup

- profiles/Albert-Debbarma.json
> Fix :Albert-Debbarma

- profiles/ginoongflores.json
> fix: add ginoongflores

- profiles/amity-ak97.json
> fix: add amity-ak97

- profiles/Pericles001.json
> fix: add Pericles001

- profiles/shinero.json
> fix: add Sarthak2143

- README.md
#1336  links this PR
resolves #1336 
---
> fixed typo mistake in readme.md file

- profiles/pushkaraj2007.json
> fix: add pushkaraj2007

- profiles/samishaikh6810.json
> fix: add samishaikh6810

- profiles/kartikver15gr8.json
Added my profile in the profile folder of awesome-github-profiles
resolves #1355 
---
> fix: add kartikver15gr8

- profiles/codewithrabeeh.json
> fix: add codewithrabeeh

- profiles/alexmihalache99.json
> fix: add AlexMihalache99

- profiles/aachal28.json
added json file
resolves #1372 
---
> fix: add aachal28

- profiles/Sumansourabh14.json
> fix: add Sumansourabh14

- profiles/akshatcoder-hash.json
> fix: add akshatcoder-hash

- Pranav-Shinde11.json
- profiles/Pranav-Shinde11.json
> fix: add Pranav-Shinde11

- profiles/leratomakhasane.json
> fix: add leratomakhasane

- profiles/ShubhamJagtap2000.json
> fix: add ShubhamJagtap2000

- profiles/PavlosIsaris.json
> fix: add PavlosIsaris

- profiles/yash-seth.json
> fix: add yash-seth

- profiles/Iamthevk.json
> fix: add Iamthevk

- profiles/E-fais.json
> fix:add E-fais

- profiles/AlphaVS-76.json
> fix: add AlphaVS-76

- profiles/shivam-jha2712.json
resolve #1412
resolves #1412 
---
> fix: add shivam-jha2712

- profiles/Mrinank-Bhowmick.json
> fix: add Mrinank-Bhowmick

- profiles/rushi-d3cod3r.json
> Fix: add rushi-d3cod3r.json

- profiles/ZahraShahid.json
> fix: add ZahraShahid

- profiles/razanjoshi.json
> fix: add razanjoshi

- axxel-devanda.json
- profiles/axxel-devanda.json
resolves #1418
- [ v] Name the PR `fix: add <your-username>`.
- [v ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ v] You've linked the PR to the correct issue.
---
> fix: add axxel-devanda

- profiles/blackkspydo.json
> fix: blackkspydo

- profiles/waqarg2001.json
resolves #1458
-  [x] Name the PR `fix: add <your-username>`.
-  [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
-  [x] You've linked the PR to the correct issue.
---
> fix: add waqarg2001

- profiles/Gulshankhandale.json
> fix: Gulshankhandale

- profiles/Ayush-Kanduri.json
Add File Ayush-Kanduri.json inside the Profiles Folder
#1461 
resolves #1461 
- [✔] Name the PR `fix: add Ayush-Kanduri`.
- [✔] You've added a file named `Ayush-Kanduri.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [✔] You've linked the PR to the correct issue.
---
- [✔] Changes made in this PR are mentioned below
- [✔] Search previous suggestions before making a new one, as yours may be a duplicate.
- [✔] I acknowledge that all my contributions will be made under the project's license.
- [✔] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)
This PR Adds a File Ayush-Kanduri.json inside the Profiles Folder.
> fix: add Ayush-Kanduri

- profiles/kartikmehta8.json
> fix: add kartikmehta8

- profiles/sarika.json
> Add humsarika issue #1473

- profiles/prakhartiwari0.json
> fix: add prakhartiwari0

- profiles/ProgrammingGym.json
> fix: add ProgrammingGym

- profiles/milkshakegum.json
> fix: add milkshakegum

- profiles/Atharv181.json
> fix: add Add Atharv181

- profiles/sujal-goswami.json
> fix: add  sujal-goswami

- profiles/Adi-Abhishek.json
> fix: add Adi-Abhishek

- profiles/tinniaru3005.json
> fix: add tinniaru3005

- profiles/SebasttianDaza.json
resolves #1498 
- [ x] Name the PR `fix: add <your-username>`.
- [ x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ x] You've linked the PR to the correct issue.
---
> fix: Add SebasttianDaza

- profiles/Shivani1917.json
> fix: add Shivani1917

- profiles/nikhilbuts.json
> Fix: Added Nikhil Butani

- profiles/abhinit21.json
> fix: add abhinit21

- profiles/sarthakroy2002.json
resolves #1510
- [ ✓] Name the PR `fix: add <your-username>`.
- [✓ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [✓ ] You've linked the PR to the correct issue.
---
- [✓ ] Changes made in this PR are mentioned below
- [✓ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [✓ ] I acknowledge that all my contributions will be made under the project's license.
- [✓ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)
> fix: add sarthakroy2002

- profiles/tanmaycode2.json
> add tanmaycode2

- profiles/yigagilbert.json
> fix: add yigagilbert

- profiles/Dunsin.json
resolves #1347
---
- added my Dunsin's profile
> feat(Dunsin.json): add Dunsin's Profile

- profiles/Pranjal360Agarwal.json
resolves #1251 
I have worked on the changes suggested in the previous PR.
Please review my PR.
> Create Pranjal360Agarwal.json file

- README.md
> Outdated badge link updated on README.md

- profiles/welel.json
> fix: add welel

- profiles/abdul-wahab.json
> fix: add abdul-wahab

- profiles/thisiskaransgit.json
> add thisiskaransgit

- profiles/jepariz.json
> fix: add jepariz

- profiles/eyucoder.json
> fix: add eyucoder

- profiles/ansu647.json
> fix: add ansu647

- profiles/Arjundotadex.json
> fix: add Arjundotadex

- profiles/sheisacreative.json
resolves #1557
- [T] Name the PR `fix: add <your-username>`.
- [T] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [T] You've linked the PR to the correct issue.
> fix: add <sheisacreative>

- profiles/thalesgomest.json
> fix: add thalesgomest

- profiles/techhead.json
> fix: add techhead

- profiles/JeherillaJanwar.json
> fix: add JeherillaJanwar

- profiles/ayushigeorge.json
> fix: add ayushigeorge

- profiles/deveshp007.json
> fix: add deveshp007

- profiles/Pal-Sandeep.json
> fix: add Pal-Sandeep

- profiles/ShehrozIrfan.json
> fix: add Shehroz Irfan

- profiles/ShanmukhiKairuppala.json
> added Shanmukhikairuppala

- profiles/AliJafriETH.json
> Add AliJafriETH

- profiles/abhijeet-26.json
> abhijeet-26 profile added

- profiles/dmarsal90.json
> add dmarsal90

- profiles/HoldUpFjord.json
Resolve #1623
Big thank you to the maintainers!
---
> fix: add HoldUpFjord

- profiles/OlojaMuyiwa.json
> fix: add OlojaMuyiwa

- profiles/rupeshexe.json
> add rupeshexe

- profiles/AyushJain001.json
> Fix:  <AyushJain001>

- profiles/Siddhesh-Agarwal.json
> fix: add Siddhesh-Agarwal

- profiles/Siddhesh-Agarwal.json
> remove trailing comma

- README.md
resolves #1610 
---
- Replace the given link with the new link.
> The link to profiles is not properly given

- profiles/SamarthSaxena10.json
> fix: add SamarthSaxena10

- profiles/BoseSj.json
> fix: add BoseSj

- profiles/Abdulwahid7027.json
> fix: add<Abdulwahid7027>

- profiles/Anmol-Baranwal.json
followed the guidelines
resolves #1658 
---
> fix: add Anmol-Baranwal

- profiles/tushar-corbic.json
> fix: add tushar-corbic

- .github/workflows/prettier-lint-check.yml
> ci: Update prettier-lint-check.yml

- profiles/theselaw.json
> fix: add theselaw

- profiles/Rishav1707.json
> fix: add Rishav1707

- profiles/rakesh9100.json
> fix: add rakesh9100

- profiles/Ajay84sia.json
> fix: add <Ajay84sia>

- profiles/raghu-007.json
> fix: add raghu-007

- profiles/himanshu1221.json
> fix: add himanshu1221

- profiles/ritika728.json
> fix: add ritika728

- profiles/esha98.json
> :zap: fix: add esha98

- profiles/Tejender1521.json
> fix: add Tejender1521

- priyankarpal.json
- profiles/priyankarpal.json
> Add my Profile

- profiles/josevale99.json
> add: profile - JoseVale99

- profiles/Mvishal123.json
Created Mvishal123.json for profile addition
resolves #1681
---
> fix: add <Mvishal123>

- profiles/mukul314.json
> fix: add mukul314

- profiles/vee339.json
> fix: add Vee339 

- profiles/TusharKesarwani.json
> fix: add TusharKesarwani

- profiles/GauravBurande.json
> fix: add GauravBurande

- .github/workflows/greetings.yaml
resolves #1695 
---
- Adds greeting workflow to greet new contributors whenever they raise a issue or PR
None
> Add: greetings.yaml workflow to greet contributors

- profiles/pankajktech.json
> fix: add <pankajktech>

- profiles/chiragjh7.json
> fix: add chiragjh7

- profiles/OshekharO.json
> fix: add <OshekharO>

- profiles/Analyzings.json
> fix: add Analyzings

- profiles/OgeHub.json
> fix: add OgeHub

- profiles/camdan-me.json
> fix: add camdan-me

- profiles/NikhilRaikwar.json
> fix: add <NikhilRaikwar>

- profiles/SamMintah.json
> fix: add <SamMintah>

- profiles/abhiraj-ku.json
resolves #1741 
- [ yes] Name the PR `fix: add <your-username>`.
- [yes ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [yes ] You've linked the PR to the correct issue.
> Fix: add abhiraj-ku

- profiles/AsserELfeki.json
> fix: add <AsserELfeki>

- profiles/Shoaib19.json
> fix: add Shoaib19

- AVI-SHUKLA1110.json
> fix: add AVI-SHUKLA1110

- .github/workflows/greetings.yaml
- .github/workflows/main.yml
- .github/workflows/prettier-lint-check.yml
- Use newer actions versions.
None.
> ci: use newer actions versions

- profiles/bkpecho.json
> fix: add bkpecho

- profiles/srishti666.json
> fix: add srishti666

- profiles/getlost01.json
> fix: add <getlost01>

- profiles/lord-benjamin.json
> fix: add lord-benjamin

- profiles/CameliaD.json
> fix: add CameliaD

- profiles/rohansx.json
> fix: add rohansx

- profiles/TRohit20
> Add TRohit20

- profiles/minhaj-313.json
> fix: add <minhaj-313>

- profiles/StarKnightt.json
> fix: add <StarKnightt>

- profiles/sejosephmartin.json
resolves #1814 
- [x ] Name the PR `fix: add <your-username>`.
- [x ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
---
> fix: add <sejosephmartin>

- profiles/oyepriyansh.json
resolves #issueNumber [1816](https://github.com/EddieHubCommunity/awesome-github-profiles/issues/1816)
---
> fix: add oypriyansh

- profiles/kartikp962.json
> fix: add <kartikp962>

- profiles/ashishk1331.json
resolve #1833
resolves #1833
---
> fix: add ashishk1331

- profiles/divyanshdxn.json
> fix: add divyanshdxn

- profiles/Edlavio.json
> fix: add Edlavio

- profiles/shrey-a-gupta.json
> Fix : add shrey-a-gupta

- .github/pull_request_template.md
- README.md
> chore: `resolves` -> `closes`

- profiles/piaseckijulian.json
> fix: add piaseckijulian

- profiles/sabhisharma-ise.json
closes #1856 
---
The PR adds sabhisharma-ise.json file in profiles folder.
> fix: add sabhisharma-ise

- profiles/oluwatobiss.json
> fix: add oluwatobiss

- profiles/pragyamahajan.json
> fix: add pragyamahajan

- profiles/franciscogsilva.json
> fix: add franciscogsilva

- profiles/dave-hill.json
> fix: add isdavehill

- profiles/krushnarout.json
> fix: add krushnarout

- profiles/zul132.json
> fix: add <zul132>

- profiles/geoffreylgv.json
> fix: add geoffreylgv

- profiles/Manishak798.json
> fix: add Manishak798

- profiles/ighoshsubho.json
> fix: add ighoshsubho

- carlminier.json
- profiles/carlminier.json
> fix: add <carlminier>

- profiles/subhadeepbanerjee2003.json
closes #1899 
---
```
{
"image": "https://user-images.githubusercontent.com/116381157/262457570-69139248-1a35-416c-b2f5-40a19cf9969c.png",
"issueId": 1899,
"name": "Subhadeep Banerjee",
"username": "subhadeepbanerjee2003"
}
```
> fix: add subhadeepbanerjee2003

- profiles/Abhinav.json
closes #1888 
---
Adding Abhinav11234 Github Profile ScreenShot
Thanks For Giving me this opportunity.
> fix: add <abhinav11234>

- profiles/MehraDevesh2022.json
closes  #1891
closes #issueNumber
---
> fix : <MehraDevesh2022>

- profiles/KISHANsingh0001.json
closes #1894
closes #issueNumber
---
> fix: add KISHANsingh0001

- profiles/AyushSarode.json
closes #1895 
closes #issueNumber
---
> fix: add AyushSarode

- profiles/MaorBemdoo.json
> fix: add MaorBemdoo

- profiles/leo7736.json
closes #1902
closes #issueNumber
---
> fix: add <leo7736>

- README.md
> Manzil infinity180 patch 1 broken badge

- profiles/vigdisha.json
> fix: add <vigdisha>

- _config.yml
- Fix the favicon not showing up.
- According to this issue, looks like adding the SEO tag plugin fixes that. https://github.com/pages-themes/cayman/issues/93
None.
> Fix favicon not showing up

- profiles/WassCodeur.json
> fix: add WassCodeur

- profiles/grace-anand.json
> fix : add Anand R

- profiles/DishaKD.json
> fix: add Dishal Kanishka

- profiles/thisisrishabh22
> feat: add thisisrishabh22 profile

- profiles/zemerik.json
> fix: add Zemerik

- profiles/NamanOG.json
> fix: add NamanOG

- profiles/Kiran1689.json
> fix: add Kiran1689

- profiles/Saravanakumar2003.json
closes #1977 
---
I have added my profile.
> fix: add Saravanakumar2003

- profiles/oyin-systems.json
> fix: add oyin-systems

- profiles/Pinkuagrawal28.json
closes #1970 
---
Added My Profile
> fix: add <Pinkuagrawal28>

- profiles/AndresPradGo.json
closes #1966 
---
closes #1966
> Fix: Add AndresPradGo

- profiles/denisakp.json
> fix: add Denis AKPAGNONITE

- profiles/sahiljawale54.json
> fix: add sahiljawale54
